/**
 * Pixel Rush Cosmetic Registry
 * Data-driven definitions for Runner Skins, Hats, and Particle Trails.
 */

import { CosmeticItem, CosmeticCategory } from './cosmeticTypes';

export const COSMETIC_SKINS: CosmeticItem[] = [
  {
    id: 'classic_runner',
    name: 'Classic Runner',
    category: 'skin',
    rarity: 'common',
    description: 'The iconic golden-hoodie Pixel Rush runner.',
    unlockType: 'default',
    unlockValue: 0,
    price: 0,
    isDefault: true,
    icon: 'directions_run',
    colors: {
      primary: '#fea619',
      secondary: '#006591',
      accent: '#f43f5e',
      cap: '#006591',
      skin: '#ffe0bd',
    },
  },
  {
    id: 'cloud_cat',
    name: 'Cloud Cat',
    category: 'skin',
    rarity: 'uncommon',
    description: 'A nimble feline runner tuned for sky platforming.',
    unlockType: 'level',
    unlockValue: 3,
    price: 0,
    isDefault: false,
    icon: 'pets',
    colors: {
      primary: '#e0f2fe',
      secondary: '#0ea5e9',
      accent: '#f472b6',
      cap: '#38bdf8',
      skin: '#f8fafc',
    },
  },
  {
    id: 'forest_fox',
    name: 'Forest Fox',
    category: 'skin',
    rarity: 'rare',
    description: 'A swift woodland runner dressed in earthy emerald tones.',
    unlockType: 'coins',
    unlockValue: 1000,
    price: 1000,
    isDefault: false,
    icon: 'forest',
    colors: {
      primary: '#00b17b',
      secondary: '#006c49',
      accent: '#fea619',
      cap: '#047857',
      skin: '#fed7aa',
    },
  },
  {
    id: 'candy_runner',
    name: 'Candy Runner',
    category: 'skin',
    rarity: 'rare',
    description: 'Sweet, sugary outfit inspired by the vibrant Candy Canyon.',
    unlockType: 'coins',
    unlockValue: 1500,
    price: 1500,
    isDefault: false,
    icon: 'icecream',
    colors: {
      primary: '#f43f5e',
      secondary: '#fb7185',
      accent: '#fbbf24',
      cap: '#e11d48',
      skin: '#ffe4e6',
    },
  },
  {
    id: 'sky_runner',
    name: 'Sky Runner',
    category: 'skin',
    rarity: 'epic',
    description: 'High-altitude aerodynamic suit worn by master speedsters.',
    unlockType: 'level',
    unlockValue: 5,
    price: 0,
    isDefault: false,
    icon: 'flight',
    colors: {
      primary: '#0284c7',
      secondary: '#38bdf8',
      accent: '#38bdf8',
      cap: '#0369a1',
      skin: '#e0f2fe',
    },
  },
  {
    id: 'mecha_pip',
    name: 'Mecha Pip',
    category: 'skin',
    rarity: 'legendary',
    description: 'Futuristic pixel-plated robotic runner chassis.',
    unlockType: 'coins',
    unlockValue: 2500,
    price: 2500,
    isDefault: false,
    icon: 'smart_toy',
    colors: {
      primary: '#6366f1',
      secondary: '#818cf8',
      accent: '#a855f7',
      cap: '#4338ca',
      skin: '#e0e7ff',
    },
  },
];

export const COSMETIC_HATS: CosmeticItem[] = [
  {
    id: 'none_hat',
    name: 'No Hat',
    category: 'hat',
    rarity: 'common',
    description: 'Simple and clean without headwear.',
    unlockType: 'default',
    unlockValue: 0,
    price: 0,
    isDefault: true,
    icon: 'block',
    colors: { primary: 'transparent', secondary: 'transparent', accent: 'transparent' },
  },
  {
    id: 'cloud_cap',
    name: 'Cloud Cap',
    category: 'hat',
    rarity: 'common',
    description: 'Soft puffy cap styled after fluffy cirrus clouds.',
    unlockType: 'level',
    unlockValue: 2,
    price: 0,
    isDefault: false,
    icon: 'cloud',
    colors: { primary: '#e0f2fe', secondary: '#bae6fd', accent: '#38bdf8' },
  },
  {
    id: 'explorer_hat',
    name: 'Explorer Hat',
    category: 'hat',
    rarity: 'uncommon',
    description: 'Rugged safari fedora built for ancient jungle expeditions.',
    unlockType: 'coins',
    unlockValue: 800,
    price: 800,
    isDefault: false,
    icon: 'explore',
    colors: { primary: '#d97706', secondary: '#b45309', accent: '#78350f' },
  },
  {
    id: 'pilot_goggles',
    name: 'Pilot Goggles',
    category: 'hat',
    rarity: 'rare',
    description: 'Brass retro-futuristic aviator goggles.',
    unlockType: 'level',
    unlockValue: 4,
    price: 0,
    isDefault: false,
    icon: 'visibility',
    colors: { primary: '#3b82f6', secondary: '#1d4ed8', accent: '#fbbf24' },
  },
  {
    id: 'star_crown',
    name: 'Star Crown',
    category: 'hat',
    rarity: 'legendary',
    description: 'Golden radiant tiara awarded to top-tier champions.',
    unlockType: 'coins',
    unlockValue: 2000,
    price: 2000,
    isDefault: false,
    icon: 'crown',
    colors: { primary: '#fbbf24', secondary: '#f59e0b', accent: '#ffffff' },
  },
];

export const COSMETIC_TRAILS: CosmeticItem[] = [
  {
    id: 'none_trail',
    name: 'No Trail',
    category: 'trail',
    rarity: 'common',
    description: 'No movement trail effect.',
    unlockType: 'default',
    unlockValue: 0,
    price: 0,
    isDefault: true,
    icon: 'block',
    colors: { primary: 'transparent', secondary: 'transparent', accent: 'transparent' },
  },
  {
    id: 'cloud_trail',
    name: 'Cloud Trail',
    category: 'trail',
    rarity: 'common',
    description: 'Puffs of miniature white clouds as you sprint.',
    unlockType: 'level',
    unlockValue: 2,
    price: 0,
    isDefault: false,
    icon: 'cloud_queue',
    colors: { primary: '#ffffff', secondary: '#e0f2fe', accent: '#bae6fd' },
  },
  {
    id: 'leaf_trail',
    name: 'Leaf Trail',
    category: 'trail',
    rarity: 'uncommon',
    description: 'Swirling emerald leaves kicked up with every leap.',
    unlockType: 'level',
    unlockValue: 4,
    price: 0,
    isDefault: false,
    icon: 'eco',
    colors: { primary: '#22c55e', secondary: '#16a34a', accent: '#86efac' },
  },
  {
    id: 'spark_trail',
    name: 'Spark Trail',
    category: 'trail',
    rarity: 'rare',
    description: 'Electric golden spark particles trailing your dash.',
    unlockType: 'coins',
    unlockValue: 1200,
    price: 1200,
    isDefault: false,
    icon: 'bolt',
    colors: { primary: '#facc15', secondary: '#eab308', accent: '#fef08a' },
  },
  {
    id: 'candy_trail',
    name: 'Candy Trail',
    category: 'trail',
    rarity: 'epic',
    description: 'Colorful rainbow sugar sprinkles bouncing in your wake.',
    unlockType: 'coins',
    unlockValue: 1600,
    price: 1600,
    isDefault: false,
    icon: 'grain',
    colors: { primary: '#f43f5e', secondary: '#ec4899', accent: '#a855f7' },
  },
];

export const ALL_COSMETICS: CosmeticItem[] = [
  ...COSMETIC_SKINS,
  ...COSMETIC_HATS,
  ...COSMETIC_TRAILS,
];

export function getCosmeticById(id: string): CosmeticItem | undefined {
  return ALL_COSMETICS.find((c) => c.id === id);
}

export function getCosmeticsByCategory(category: CosmeticCategory): CosmeticItem[] {
  return ALL_COSMETICS.filter((c) => c.category === category);
}

export function getDefaultCosmetics(): { skinId: string; hatId: string; trailId: string } {
  return {
    skinId: 'classic_runner',
    hatId: 'none_hat',
    trailId: 'none_trail',
  };
}
